### ISSUE TITLE
App stuck at 'Downloading NMBS data..."

### ISSUE THREAD

**Issue by kristofwillen** [kristofwillen/Pebble-NMBS#12]
When asking info about an itinerary, the app gets stuck at "Downloading NMBS data..." after selecting from- and to-station.

**Comment by kristofwillen** [comment]
App crashes with following error : 
`[PHONE] pebble-app.js:?: [DBUG] Fetching http://api.irail.be/connections/?to=leuven&from=aarschot&format=json
[PHONE] pebble-app.js:?: JavaScript Error:
TypeError: Cannot read property 'departure' of undefined
    at parseFeed (app.js:86:41)
    at app.js:238:25
    at req.onreadystatechange (lib/ajax.js:116:9)
`

Seems like there are changes in the irail.be API...

**Comment by kristofwillen** [comment]
Number of received result has been lowered, falling below the assumed minimum of 5.
I'm pushing a bugfix which calculates dynamically the result size.

**Comment by kristofwillen** [comment]
Fixed in version 1.5 - uploaded to Pebble Store.
